### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by iver56** [stet-stet/DDD#1]
Hi! Thanks for sharing your code. I noticed that the repository does not have a license file yet, so it's not clear if people can contribute to or use your code. If you prefer a simple and permissive license, you can add a `LICENSE` file with content like this: https://choosealicense.com/licenses/mit/

Here's an example of such a license file in the pyloudnorm repo: https://github.com/csteinmetz1/pyloudnorm/blob/master/LICENSE

**Comment by stet-stet** [comment]
Thank you @iver56 for pointing this out! A MIT license file has been added.
